// src/components/CreatePostForm/CreatePostForm.vue
<template>
  <v-form
    class="create-post-form"
    @submit.prevent="submitHandler"
    ref="form"
    :disabled="submitInProgress"
  >
    <div class="create-post-form--input-area">
      <v-text-field
        v-model="model.content"
        :rules="rules.content"
        placeholder="Что происходит?"
        outlined
      />
    </div>
    <v-btn color="primary" type="submit" x-large :loading="submitInProgress">
      Поделиться
    </v-btn>
  </v-form>
</template>

<script lang="ts">
import Vue from "vue";
import { ISubmitCallback } from "./types";

type FormRef = {
  validate(): boolean;
  resetValidation(): void;
};

export default Vue.extend({
  name: "CreatePostForm",
  data() {
    return {
      submitInProgress: false,
      model: {
        content: ""
      },
      rules: {
        content: [
          (value: string | undefined) => !!value || "Сообщение обязательно"
        ]
      }
    };
  },
  props: {
    onSubmit: {
      type: (Function as unknown) as () => ISubmitCallback,
      required: true
    }
  },
  methods: {
    submitHandler() {
      const formRef = (this.$refs.form as unknown) as FormRef;

      if (!formRef.validate()) {
        return;
      }

      this.submitInProgress = true;
      this.onSubmit(this.model)
        .then(() => {
          this.resetModel();
          formRef.resetValidation();
        })
        .catch(error => {
          throw error;
        })
        .finally(() => {
          this.submitInProgress = false;
        });
    },
    resetModel() {
      this.model.content = "";
    }
  }
});
</script>

<style lang="sass">
@import "./create-post-form.sass"
</style>

// applications/tasty-twitter-react/src/components/CreatePostForm/CreatePostForm.tsx
import React, {FormEvent, useState} from 'react'
import './create-post-form.sass'
import { CreatePostFormProps } from './types';

export const CreatePostForm: React.FC<CreatePostFormProps> = ({ onSubmit }) => {
  const [message, setMessage] = useState<string>('');

  const [submitInProgress, setSubmitInProgress] = useState<boolean>(false);

  const changeHandler: React.ChangeEventHandler<HTMLInputElement> = (event) => {
    setMessage(event.target.value.trim());
  };

  const submitHandler: React.ChangeEventHandler<FormEvent> = (event) => {
    event.preventDefault()
    setSubmitInProgress(true)
    onSubmit({ content: message })
      .then(() => {
        setMessage('')
      })
      .finally(() => {
        setSubmitInProgress(false)
      })
  }

  return (
    <form className='create-post-form' onSubmit={submitHandler}>
      <div className='create-post-form__input-area'>
        <input
          className='create-post-form__input'
          type='text'
          placeholder='Что происходит?'
          onChange={changeHandler}
          disabled={submitInProgress}
        />
      </div>
      <div className='create-post-form__submit-area'>
        <button
          className='create-post-form__submit'
          type='submit'
          disabled={submitInProgress}
        >
          Поделиться
        </button>
      </div>
    </form>
  )
}
